In [2]:
import numpy as np
m = 100
X = 6 * np.random.rand(m,1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m,1)

In [3]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1, solver="cholesky") #Ridge Regression using a closed-form solution using matrix factorization techiniques by Cholesky
ridge_reg.fit(X,y)
ridge_reg.predict([[1.5]])

array([[ 5.28127865]])

In [4]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(penalty="l2") #using SGD and use the L2 norm regulation
sgd_reg.fit(X,y.ravel()) 
sgd_reg.predict([[1.5]])

C:\Users\moonl\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


array([ 4.60280826])

In [5]:
from sklearn.linear_model import Lasso #
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X,y)
lasso_reg.predict([[1.5]])

array([ 5.25020488])

In [6]:
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5) #l1_ratio corresponds to the mix ratio r
elastic_net.fit(X,y)
elastic_net.predict([[1.5]])

array([ 5.24813014])

In [7]:
from sklearn.base import clone  # early stopping 
sgd_reg = SGDRegressor(n_iter=1, warm_start=True, penalty=None, learning_rate="constant", eta0=0.0005) # with warm_start = True, when fit() is called, it just continues training where it left off instead of restarting from scratch

In [8]:
minimum_val_error = float("inf")
best_epoch = None
best_model = None
for epoch in range(1000):
    sgd_reg.fit(X_train_poly_scaled, y_train)  #continues where it left off
    y_val_predict = sgd_reg.predict(X_val_poly_scaled)
    val_error =  mean_squared_error(y_val_predict,y_val)
    if val_error < minimum_val_error:
        minimum_val_error = val_error
        best_epoch = epoch
        best_model = clone(sgd_reg)

NameError: name 'X_train_poly_scaled' is not defined

In [9]:
from sklearn import datasets  # use iris example to do Logistic Regression
iris = datasets.load_iris()

In [14]:
list(iris.keys())

['DESCR', 'target', 'target_names', 'data', 'feature_names']

In [15]:
X = iris["data"][:,3:] # petal width
y = (iris["target"] == 2).astype(np.int)

In [17]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
# let's look at the model's estimated probabilities for flowers with petal widths varing from 0 to 3 cm
import matplotlib.pyplot as plt
X_new = np.linspace(0,3,1000).reshape(-1,1)
y_proba = log_reg.predict_proba(X_new)
plt.plot(X_new, y_proba[:,1], "g-", label = "Iris-Virginica")
plt.plot(X_new, y_proba[:,0], "b--", label = "NOT Iris-Virginica")

In [24]:
# use Softmax Regression to classify iris flowers into three classes 
X = iris["data"][:,(2,3)] # petal length, petal width
y = iris["target"]
softmax_reg = LogisticRegression(multi_class="multinomial",solver="lbfgs",C=10)
softmax_reg.fit(X,y)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
softmax_reg.predict([[5,2]])


array([2])

In [26]:
softmax_reg.predict_proba([[5,2]])

array([[  6.33134077e-07,   5.75276067e-02,   9.42471760e-01]])